[2024-10-10T11:29:36.497+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-10T11:29:36.505+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_hooks.monitoring manual__2024-10-10T11:28:55.307312+00:00 [queued]>
[2024-10-10T11:29:36.509+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_hooks.monitoring manual__2024-10-10T11:28:55.307312+00:00 [queued]>
[2024-10-10T11:29:36.509+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-10T11:29:36.513+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): monitoring> on 2024-10-10 11:28:55.307312+00:00
[2024-10-10T11:29:36.519+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=6451) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-10T11:29:36.520+0000] {standard_task_runner.py:64} INFO - Started process 6462 to run task
[2024-10-10T11:29:36.521+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_hooks', 'monitoring', 'manual__2024-10-10T11:28:55.307312+00:00', '--job-id', '1087', '--raw', '--subdir', 'DAGS_FOLDER/Stock_pred.py', '--cfg-path', '/tmp/tmpimwf9jp5']
[2024-10-10T11:29:36.521+0000] {standard_task_runner.py:91} INFO - Job 1087: Subtask monitoring
[2024-10-10T11:29:36.540+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_postgres_hooks.monitoring manual__2024-10-10T11:28:55.307312+00:00 [running]> on host b7aba691e1ff
[2024-10-10T11:29:36.570+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_with_postgres_hooks' AIRFLOW_CTX_TASK_ID='monitoring' AIRFLOW_CTX_EXECUTION_DATE='2024-10-10T11:28:55.307312+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-10T11:28:55.307312+00:00'
[2024-10-10T11:29:36.571+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-10T11:29:36.574+0000] {base.py:84} INFO - Using connection ID 'postgres_server_2' for task execution.
[2024-10-10T11:29:36.609+0000] {warnings.py:112} WARNING - /opt/***/dags/Stock_pred.py:428: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_old_clf['Target'].iloc[-1] = input_clf['Target']

[2024-10-10T11:29:36.644+0000] {logging_mixin.py:188} INFO -                     Date  CLOSE_diff_t+1                      New_Prediction_ts
0    2022-02-24 00:00:00      -56.133410                             -39.024616
1    2022-02-25 00:00:00     -252.600345                            -132.841003
2    2022-02-28 00:00:00      -28.066705                             -37.190056
3    2022-03-01 00:00:00     -533.267395                             -206.79863
4    2022-03-02 00:00:00      308.733755                             110.723549
..                   ...             ...                                    ...
605  2024-07-30 00:00:00      400.000000                              10.340194
606  2024-07-31 00:00:00     -600.000000                            -188.112778
607  2024-08-01 00:00:00        0.000000                             -12.042727
608  2024-08-02 00:00:00     -750.000000                              -9.038181
0             2024-10-10             NaN     predicted_index
0      -124.238213

[610 rows x 3 columns]
[2024-10-10T11:29:36.645+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-10T11:29:36.645+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Stock_pred.py", line 446, in monitoring
    df_concat_clf.drop_duplicates(keep='last',inplace=True)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 6566, in drop_duplicates
    result = self[-self.duplicated(subset, keep=keep)]
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 6706, in duplicated
    labels, shape = map(list, zip(*map(f, vals)))
                              ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 6674, in f
    labels, shape = algorithms.factorize(vals, size_hint=len(self))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/algorithms.py", line 795, in factorize
    codes, uniques = factorize_array(
                     ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/algorithms.py", line 595, in factorize_array
    uniques, codes = table.factorize(
                     ^^^^^^^^^^^^^^^^
  File "pandas/_libs/hashtable_class_helper.pxi", line 7280, in pandas._libs.hashtable.PyObjectHashTable.factorize
  File "pandas/_libs/hashtable_class_helper.pxi", line 7194, in pandas._libs.hashtable.PyObjectHashTable._unique
TypeError: unhashable type: 'DataFrame'
[2024-10-10T11:29:36.649+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dag_with_postgres_hooks, task_id=monitoring, run_id=manual__2024-10-10T11:28:55.307312+00:00, execution_date=20241010T112855, start_date=20241010T112936, end_date=20241010T112936
[2024-10-10T11:29:36.653+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1087 for task monitoring (unhashable type: 'DataFrame'; 6462)
[2024-10-10T11:29:36.700+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-10-10T11:29:36.707+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-10T11:29:36.708+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
