[2024-07-10T09:28:54.942+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-10T09:28:54.951+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_hooks.predict manual__2024-07-10T09:28:47.551323+00:00 [queued]>
[2024-07-10T09:28:54.954+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_hooks.predict manual__2024-07-10T09:28:47.551323+00:00 [queued]>
[2024-07-10T09:28:54.954+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-10T09:28:54.959+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): predict> on 2024-07-10 09:28:47.551323+00:00
[2024-07-10T09:28:54.962+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=3361) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-10T09:28:54.962+0000] {standard_task_runner.py:63} INFO - Started process 3370 to run task
[2024-07-10T09:28:54.963+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_hooks', 'predict', 'manual__2024-07-10T09:28:47.551323+00:00', '--job-id', '403', '--raw', '--subdir', 'DAGS_FOLDER/sql_2.py', '--cfg-path', '/tmp/tmpior9_09j']
[2024-07-10T09:28:54.963+0000] {standard_task_runner.py:91} INFO - Job 403: Subtask predict
[2024-07-10T09:28:54.978+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_postgres_hooks.predict manual__2024-07-10T09:28:47.551323+00:00 [running]> on host 10d335c2a089
[2024-07-10T09:28:55.008+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_with_postgres_hooks' AIRFLOW_CTX_TASK_ID='predict' AIRFLOW_CTX_EXECUTION_DATE='2024-07-10T09:28:47.551323+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-10T09:28:47.551323+00:00'
[2024-07-10T09:28:55.009+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-10T09:28:55.129+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/mlflow/store/artifact/utils/models.py:32: FutureWarning: ``mlflow.tracking.client.MlflowClient.get_latest_versions`` is deprecated since 2.9.0. Model registry stages will be removed in a future major release. To learn more about the deprecation of model registry stages, see our migration guide here: https://mlflow.org/docs/latest/model-registry.html#migrating-from-stages
  latest = client.get_latest_versions(name, None if stage is None else [stage])

[2024-07-10T09:28:55.138+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-10T09:28:55.139+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/sql_2.py", line 229, in predict
    model = mlflow.sklearn.load_model(model_uri)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/mlflow/sklearn/__init__.py", line 626, in load_model
    local_model_path = _download_artifact_from_uri(artifact_uri=model_uri, output_path=dst_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/mlflow/tracking/artifact_utils.py", line 108, in _download_artifact_from_uri
    repo = get_artifact_repository(artifact_uri=root_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/mlflow/store/artifact/artifact_repository_registry.py", line 124, in get_artifact_repository
    return _artifact_repository_registry.get_artifact_repository(artifact_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/mlflow/store/artifact/artifact_repository_registry.py", line 77, in get_artifact_repository
    return repository(artifact_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/mlflow/store/artifact/models_artifact_repo.py", line 59, in __init__
    ) = ModelsArtifactRepository._get_model_uri_infos(artifact_uri)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/mlflow/store/artifact/models_artifact_repo.py", line 93, in _get_model_uri_infos
    name, version = get_model_name_and_version(client, uri)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/mlflow/store/artifact/utils/models.py", line 94, in get_model_name_and_version
    return model_name, str(_get_latest_model_version(client, model_name, model_stage))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/mlflow/store/artifact/utils/models.py", line 32, in _get_latest_model_version
    latest = client.get_latest_versions(name, None if stage is None else [stage])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/mlflow/utils/annotations.py", line 145, in deprecated_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/mlflow/tracking/client.py", line 3468, in get_latest_versions
    return self._get_registry_client().get_latest_versions(name, stages)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/mlflow/tracking/_model_registry/client.py", line 152, in get_latest_versions
    return self.store.get_latest_versions(name, stages)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/mlflow/store/model_registry/file_store.py", line 425, in get_latest_versions
    raise MlflowException(
mlflow.exceptions.MlflowException: Registered Model with name=Model1 not found
[2024-07-10T09:28:55.146+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dag_with_postgres_hooks, task_id=predict, run_id=manual__2024-07-10T09:28:47.551323+00:00, execution_date=20240710T092847, start_date=20240710T092854, end_date=20240710T092855
[2024-07-10T09:28:55.151+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 403 for task predict (Registered Model with name=Model1 not found; 3370)
[2024-07-10T09:28:55.183+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-10T09:28:55.193+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-10T09:28:55.194+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
