[2024-10-10T11:23:24.490+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-10T11:23:24.500+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_hooks.monitoring manual__2024-10-10T11:22:41.011281+00:00 [queued]>
[2024-10-10T11:23:24.504+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_hooks.monitoring manual__2024-10-10T11:22:41.011281+00:00 [queued]>
[2024-10-10T11:23:24.504+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-10T11:23:24.509+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): monitoring> on 2024-10-10 11:22:41.011281+00:00
[2024-10-10T11:23:24.514+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=5735) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-10T11:23:24.515+0000] {standard_task_runner.py:64} INFO - Started process 5760 to run task
[2024-10-10T11:23:24.515+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_hooks', 'monitoring', 'manual__2024-10-10T11:22:41.011281+00:00', '--job-id', '1060', '--raw', '--subdir', 'DAGS_FOLDER/Stock_pred.py', '--cfg-path', '/tmp/tmp78nu58eg']
[2024-10-10T11:23:24.516+0000] {standard_task_runner.py:91} INFO - Job 1060: Subtask monitoring
[2024-10-10T11:23:24.534+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_postgres_hooks.monitoring manual__2024-10-10T11:22:41.011281+00:00 [running]> on host b7aba691e1ff
[2024-10-10T11:23:24.566+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_with_postgres_hooks' AIRFLOW_CTX_TASK_ID='monitoring' AIRFLOW_CTX_EXECUTION_DATE='2024-10-10T11:22:41.011281+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-10T11:22:41.011281+00:00'
[2024-10-10T11:23:24.567+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-10T11:23:24.570+0000] {base.py:84} INFO - Using connection ID 'postgres_server_2' for task execution.
[2024-10-10T11:23:24.603+0000] {warnings.py:112} WARNING - /opt/***/dags/Stock_pred.py:428: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_old_clf['Target'].iloc[-1] = input_clf['Target']

[2024-10-10T11:23:24.638+0000] {logging_mixin.py:188} INFO -       OPEN  HIGH  LOW  CLOSE  ...  pvt      pvt_ema9  typical_price  CLOSE_diff1
1000   NaN   NaN  NaN    NaN  ...  NaN  4.964409e+07            NaN          NaN

[1 rows x 25 columns]
[2024-10-10T11:23:24.639+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-10T11:23:24.639+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3791, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 152, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 181, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: -1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Stock_pred.py", line 441, in monitoring
    df_old_ts['CLOSE_diff_t+1'].iloc[-1] = input_ts[-1]
                                           ~~~~~~~~^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 3893, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3798, in get_loc
    raise KeyError(key) from err
KeyError: -1
[2024-10-10T11:23:24.644+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dag_with_postgres_hooks, task_id=monitoring, run_id=manual__2024-10-10T11:22:41.011281+00:00, execution_date=20241010T112241, start_date=20241010T112324, end_date=20241010T112324
[2024-10-10T11:23:24.649+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1060 for task monitoring (-1; 5760)
[2024-10-10T11:23:24.695+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-10-10T11:23:24.702+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-10T11:23:24.703+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
