[2024-07-17T08:28:20.205+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-17T08:28:20.213+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_hooks.concat_data manual__2024-07-17T08:28:16.980312+00:00 [queued]>
[2024-07-17T08:28:20.215+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_hooks.concat_data manual__2024-07-17T08:28:16.980312+00:00 [queued]>
[2024-07-17T08:28:20.216+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-17T08:28:20.221+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): concat_data> on 2024-07-17 08:28:16.980312+00:00
[2024-07-17T08:28:20.223+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=711) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-17T08:28:20.224+0000] {standard_task_runner.py:63} INFO - Started process 720 to run task
[2024-07-17T08:28:20.224+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_hooks', 'concat_data', 'manual__2024-07-17T08:28:16.980312+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/sql_2.py', '--cfg-path', '/tmp/tmpmqb8wu01']
[2024-07-17T08:28:20.225+0000] {standard_task_runner.py:91} INFO - Job 58: Subtask concat_data
[2024-07-17T08:28:20.240+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_postgres_hooks.concat_data manual__2024-07-17T08:28:16.980312+00:00 [running]> on host 8d28ae2d2ca1
[2024-07-17T08:28:20.265+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_with_postgres_hooks' AIRFLOW_CTX_TASK_ID='concat_data' AIRFLOW_CTX_EXECUTION_DATE='2024-07-17T08:28:16.980312+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-17T08:28:16.980312+00:00'
[2024-07-17T08:28:20.265+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-17T08:28:20.268+0000] {base.py:84} INFO - Using connection ID 'postgres_server_2' for task execution.
[2024-07-17T08:28:20.426+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-17T08:28:20.427+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-17T08:28:20.430+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_hooks, task_id=concat_data, run_id=manual__2024-07-17T08:28:16.980312+00:00, execution_date=20240717T082816, start_date=20240717T082820, end_date=20240717T082820
[2024-07-17T08:28:20.446+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-17T08:28:20.456+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-17T08:28:20.457+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
