[2024-12-09T10:11:12.273+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-09T10:11:12.338+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_hooks.get_src_tables scheduled__2024-11-03T13:30:00+00:00 [queued]>
[2024-12-09T10:11:12.375+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_hooks.get_src_tables scheduled__2024-11-03T13:30:00+00:00 [queued]>
[2024-12-09T10:11:12.380+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-12-09T10:11:12.441+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_src_tables> on 2024-11-03 13:30:00+00:00
[2024-12-09T10:11:12.490+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=93) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-09T10:11:12.493+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_hooks', 'get_src_tables', 'scheduled__2024-11-03T13:30:00+00:00', '--job-id', '1294', '--raw', '--subdir', 'DAGS_FOLDER/Stock_pred.py', '--cfg-path', '/tmp/tmpf2c_i3hn']
[2024-12-09T10:11:12.496+0000] {standard_task_runner.py:64} INFO - Started process 274 to run task
[2024-12-09T10:11:12.496+0000] {standard_task_runner.py:91} INFO - Job 1294: Subtask get_src_tables
[2024-12-09T10:11:17.762+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_postgres_hooks.get_src_tables scheduled__2024-11-03T13:30:00+00:00 [running]> on host b7aba691e1ff
[2024-12-09T10:11:17.982+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_with_postgres_hooks' AIRFLOW_CTX_TASK_ID='get_src_tables' AIRFLOW_CTX_EXECUTION_DATE='2024-11-03T13:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-03T13:30:00+00:00'
[2024-12-09T10:11:17.984+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-09T10:11:18.025+0000] {base.py:84} INFO - Using connection ID 'postgres_server_2' for task execution.
[2024-12-09T10:11:18.302+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/providers/common/sql/hooks/sql.py:269: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return psql.read_sql(sql, con=conn, params=parameters, **kwargs)

[2024-12-09T10:11:36.178+0000] {local_task_job_runner.py:243} INFO - Task exited with return code -9For more information, see https://***.apache.org/docs/apache-***/stable/troubleshooting.html#LocalTaskJob-killed
[2024-12-09T10:11:36.312+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-09T10:11:36.315+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
